{% set name = "lsst-versions" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lsst-versions-{{ version }}.tar.gz
  sha256: e111718a5a13a9552648c71e78edb5a480dbf02d6733ba1424dff7650b491066

build:
  entry_points:
    - lsst-version = lsst_versions._cmd:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env: PYTHONUTF8=1
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - tomli >1.0
    - gitpython
    - packaging
    - pip
  run:
    - python >={{ python_min }}
    - setuptools >=46.0
    - tomli >1.0.0
    - gitpython >=3.1
    - packaging

test:
  imports:
    - lsst_versions
  commands:
    - pip check
    - lsst-version --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lsst/lsst_versions
  summary: Calculate package versions following LSST code conventions.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - erykoff
    - timj
    - TallJimbo
    - camposandro
